project_id = "gewwxdmxrwyosddczezg"

[functions."scrape-saps-wanted"]
verify_jwt = false

[functions."search-criminal-records"]
verify_jwt = false

[functions."import-wanted-persons"]
verify_jwt = false

[functions."submit-payment"]
verify_jwt = false
