project_id = "gewwxdmxrwyosddczezg"

[functions."scrape-saps-wanted"]
verify_jwt = false

[functions."scrape-saps-details"]
verify_jwt = false

[functions."multi-parameter-search"]
verify_jwt = false

[functions."import-wanted-persons"]
verify_jwt = false

[functions."submit-payment"]
verify_jwt = false

[functions."verify-admin"]
verify_jwt = false

[functions."import-opensanctions"]
verify_jwt = false

[functions."admin-verify-payment"]
verify_jwt = false

[functions."send-email"]
verify_jwt = false

[functions."import-sapswanted"]
verify_jwt = false

[functions."extract-gazette"]
verify_jwt = false

[functions."payfast-itn"]
verify_jwt = false

[functions."create-payfast-payment"]
verify_jwt = false

[functions."index-saflii"]
verify_jwt = false
