import jsPDF from 'jspdf';

interface AffidavitData {
  fullName: string;
  idNumber?: string;
  address: string;
  phone?: string;
  purpose: string;
  aboutPerson?: string;
  relationship?: string;
  statementText: string;
  reliefSought: string[];
  otherRelief?: string;
}

export function generateAffidavitPDF(data: AffidavitData): void {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pw = 210, margin = 25, cw = pw - margin * 2;
  let y = 0;

  const checkPage = (needed: number) => {
    if (y + needed > 270) { doc.addPage(); y = 25; }
  };

  // Header
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.setFont('helvetica', 'italic');
  doc.text('DRAFT AFFIDAVIT', pw - margin, 15, { align: 'right' });
  doc.text('Generated by RedFlaq', pw - margin, 20, { align: 'right' });
  doc.text(`Date: ${new Date().toLocaleDateString('en-ZA')}`, pw - margin, 25, { align: 'right' });

  // Court stamp space
  y = 35;
  doc.setDrawColor(180);
  doc.setLineWidth(0.5);
  doc.rect(margin + 20, y, cw - 40, 20);
  doc.setFontSize(8);
  doc.setTextColor(160);
  doc.setFont('helvetica', 'normal');
  doc.text('[SPACE FOR COURT STAMP/HEADING]', pw / 2, y + 10, { align: 'center' });
  doc.text('To be completed by Commissioner', pw / 2, y + 15, { align: 'center' });
  y += 28;

  // Title
  doc.setFontSize(16);
  doc.setTextColor(40);
  doc.setFont('helvetica', 'bold');
  doc.text('AFFIDAVIT', margin, y);
  doc.setDrawColor(40);
  doc.setLineWidth(1);
  doc.line(margin, y + 2, margin + 50, y + 2);
  y += 12;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('I, THE UNDERSIGNED,', margin, y);
  y += 10;

  // Deponent details
  doc.setFontSize(10);
  const addDetail = (label: string, value: string) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(value, cw - 50);
    doc.text(lines, margin + 48, y);
    y += Math.max(7, lines.length * 5) + 1;
  };

  addDetail('Full Name', data.fullName.toUpperCase());
  addDetail('Identity Number', data.idNumber || '___________________');
  addDetail('Residential Address', data.address);
  if (data.phone) addDetail('Contact Number', data.phone);
  y += 3;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('do hereby make oath/affirm and state that:', margin, y);
  y += 10;

  // Auto-generated opening paragraphs
  let paraNum = 1;
  const addPara = (text: string) => {
    checkPage(15);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(`${paraNum}. ${text}`, cw);
    for (const line of lines) {
      checkPage(6);
      doc.text(line, margin, y);
      y += 5.5;
    }
    y += 3;
    paraNum++;
  };

  addPara('I am the Deponent/Applicant in this matter. I am over the age of 18 years and legally competent to make this affidavit.');
  addPara('The facts stated herein are within my personal knowledge and belief and are, to the best of my knowledge, true and correct. Where I make statements based on information received, I believe such information to be true and correct.');
  addPara(`This affidavit is made in support of: ${data.purpose}.`);

  if (data.aboutPerson) {
    addPara(`This affidavit concerns ${data.aboutPerson}${data.relationship ? `, who is my ${data.relationship}` : ''}.`);
  }

  // User statement - split into paragraphs
  const userParas = data.statementText.split('\n').filter(p => p.trim());
  for (const para of userParas) {
    const cleaned = para.replace(/^\d+[\.\)]\s*/, ''); // remove existing numbering
    addPara(cleaned);
  }

  // Relief sought
  if (data.reliefSought.length > 0) {
    checkPage(20);
    const reliefIntro = `Based on the facts set out above, I respectfully request the following relief:`;
    const introLines = doc.splitTextToSize(`${paraNum}. ${reliefIntro}`, cw);
    for (const line of introLines) {
      checkPage(6);
      doc.text(line, margin, y);
      y += 5.5;
    }
    y += 2;

    let letter = 'a';
    for (const relief of data.reliefSought) {
      checkPage(8);
      const rLines = doc.splitTextToSize(`(${letter}) ${relief}`, cw - 10);
      for (const rl of rLines) {
        checkPage(6);
        doc.text(rl, margin + 5, y);
        y += 5.5;
      }
      letter = String.fromCharCode(letter.charCodeAt(0) + 1);
    }
    if (data.otherRelief) {
      checkPage(8);
      const oLines = doc.splitTextToSize(`(${letter}) ${data.otherRelief}`, cw - 10);
      for (const ol of oLines) { doc.text(ol, margin + 5, y); y += 5.5; }
    }
    y += 3;
    paraNum++;
  }

  addPara('I submit this affidavit in support of the above application/report and confirm that I am aware of the contents hereof.');
  addPara('I understand that making a false statement in an affidavit is a criminal offence.');

  // Signature blocks
  checkPage(60);
  y += 10;
  doc.setLineWidth(0.5);
  doc.setDrawColor(80);
  doc.line(margin, y, margin + 70, y);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text("DEPONENT'S SIGNATURE", margin, y + 5);
  y += 12;
  doc.setFont('helvetica', 'normal');
  doc.text('Signed at: _________________________', margin, y);
  y += 7;
  doc.text('On this date: ______________________', margin, y);
  y += 15;

  // Commissioner block
  checkPage(70);
  doc.line(margin, y, margin + 70, y);
  doc.setFont('helvetica', 'bold');
  doc.text('COMMISSIONER OF OATHS', margin, y + 5);
  y += 12;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const commText = [
    'I CERTIFY that the Deponent has acknowledged that:',
    '- They know and understand the contents of this affidavit;',
    '- They have no objection to taking the prescribed oath/affirmation;',
    '- They consider the oath/affirmation to be binding on their conscience;',
    '- This affidavit was sworn/affirmed before me at _________________',
    '  on this _____ day of _____________ 20___.',
    '',
    'Full Name: _______________________',
    'Designation: _____________________',
    'Signature: _______________________',
  ];
  for (const ct of commText) {
    checkPage(6);
    doc.text(ct, margin, y);
    y += 5;
  }

  // Stamp box
  checkPage(25);
  y += 5;
  doc.setDrawColor(150);
  doc.rect(margin + 30, y, 50, 20);
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('[SPACE FOR STAMP]', margin + 55, y + 11, { align: 'center' });

  // Guidance page
  doc.addPage();
  y = 15;
  doc.setFillColor(124, 58, 237);
  doc.rect(0, y, pw, 12, 'F');
  doc.setTextColor(255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('WHAT TO DO WITH THIS AFFIDAVIT', pw / 2, y + 9, { align: 'center' });
  y += 20;

  doc.setTextColor(40);
  doc.setFontSize(10);
  const steps = [
    ['STEP 1: PRINT THIS DOCUMENT', 'Print all pages of this affidavit. Do not sign it yet.'],
    ['STEP 2: GATHER REQUIRED DOCUMENTS', 'You will need: This printed affidavit (unsigned), your original SA ID document, and any supporting documents.'],
    ['STEP 3: FIND A COMMISSIONER OF OATHS', 'Available at: Any police station (FREE), any magistrates court (FREE), attorneys\' offices (may charge R50-R150), some banks (FREE for account holders).'],
    ['STEP 4: SWEAR/AFFIRM THE AFFIDAVIT', 'The Commissioner will ask you to confirm you understand the document. You will sign in their presence and they will stamp it.'],
    ['STEP 5: GET CERTIFIED COPIES', 'Ask the Commissioner to certify 2-3 copies for police, court, your lawyer, and your records.'],
    ['STEP 6: USE YOUR AFFIDAVIT', 'Once signed and stamped, use it to support protection orders, police reports, court proceedings, or workplace complaints.'],
  ];

  for (const [title, desc] of steps) {
    checkPage(18);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(desc, cw);
    for (const l of lines) { doc.text(l, margin, y); y += 5; }
    y += 4;
  }

  checkPage(25);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(124, 58, 237);
  doc.text('GET LEGAL HELP:', margin, y);
  y += 6;
  doc.setTextColor(40);
  doc.setFont('helvetica', 'normal');
  doc.text('Legal Aid South Africa (free): 0800 110 110', margin, y); y += 5;
  doc.text('GBV Command Centre (24/7): 0800 428 428', margin, y); y += 5;
  doc.text('SAPS Emergency: 10111', margin, y);

  // Footers
  const pg = doc.getNumberOfPages();
  for (let i = 1; i <= pg; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text('Draft affidavit generated by RedFlaq', margin, 285);
    doc.text(`Page ${i} of ${pg}`, pw - margin, 285, { align: 'right' });
    doc.setFontSize(6);
    doc.text('This document must be signed before a Commissioner of Oaths to become a legal affidavit.', pw / 2, 289, { align: 'center' });
    doc.text('Commissioners are available at police stations, magistrates courts, attorneys\' offices, banks.', pw / 2, 292, { align: 'center' });
  }

  const firstName = data.fullName.split(' ')[0];
  doc.save(`RedFlaq_Affidavit_${new Date().toISOString().split('T')[0]}_${firstName}.pdf`);
}
