import jsPDF from 'jspdf';

interface CertificateData {
  entry: {
    id: string;
    entry_date: string;
    entry_time: string;
    incident_description: string;
    about_person?: string | null;
    abuse_types?: string[] | null;
    weapon_involved?: boolean | null;
    weapon_description?: string | null;
    medical_attention?: boolean | null;
    medical_details?: string | null;
    police_reported?: boolean | null;
    police_case_number?: string | null;
    children_present?: boolean | null;
    location?: string | null;
    witnesses?: string | null;
    injuries_damage?: string | null;
    emotional_state?: string | null;
    statement_hash?: string | null;
    hash_generated_at?: string | null;
    created_at: string;
  };
  evidence?: {
    file_name: string;
    file_type: string;
    file_size: number;
    file_hash?: string | null;
    uploaded_at?: string | null;
  }[];
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' });
}

function formatDateTime(dateStr: string): string {
  return new Date(dateStr).toLocaleString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit', timeZoneName: 'short' });
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export function generateVerificationCertificate(data: CertificateData): void {
  const { entry, evidence = [] } = data;
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = 210;
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;
  let pageNum = 1;
  const totalPages = () => doc.getNumberOfPages();

  const addFooter = () => {
    const pg = doc.getNumberOfPages();
    for (let i = 1; i <= pg; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(128);
      doc.text('Generated by RedFlaq · redflaq.com', margin, 285);
      doc.text(`Generated on: ${new Date().toLocaleString('en-ZA')}`, pageWidth / 2, 285, { align: 'center' });
      doc.text(`Page ${i} of ${pg}`, pageWidth - margin, 285, { align: 'right' });
      doc.setFontSize(7);
      doc.text('FOR YOUR SAFETY DECISIONS ONLY — PRIVATE AND CONFIDENTIAL', pageWidth / 2, 290, { align: 'center' });
    }
  };

  const checkPage = (needed: number) => {
    if (y + needed > 270) {
      doc.addPage();
      y = 20;
    }
  };

  // Header
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, pageWidth, 25, 'F');
  doc.setTextColor(255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('RedFlaq', margin, 16);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('VERIFIED SAFETY RECORD', pageWidth - margin, 16, { align: 'right' });
  
  doc.setDrawColor(124, 58, 237);
  doc.setLineWidth(1);
  doc.line(margin, 27, pageWidth - margin, 27);
  y = 33;

  // Section 1: Document Details
  doc.setFillColor(237, 233, 254);
  doc.rect(margin, y, contentWidth, 45, 'F');
  doc.setTextColor(60);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  const detailsY = y + 8;
  doc.text('Document Type:', margin + 5, detailsY);
  doc.setFont('helvetica', 'normal');
  doc.text('RedFlaq Verified Safety Record', margin + 50, detailsY);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Entry ID:', margin + 5, detailsY + 7);
  doc.setFont('helvetica', 'normal');
  doc.text(entry.id, margin + 50, detailsY + 7);

  doc.setFont('helvetica', 'bold');
  doc.text('Verified On:', margin + 5, detailsY + 14);
  doc.setFont('helvetica', 'normal');
  doc.text(entry.hash_generated_at ? formatDateTime(entry.hash_generated_at) : 'Pending', margin + 50, detailsY + 14);

  doc.setFont('helvetica', 'bold');
  doc.text('Method:', margin + 5, detailsY + 21);
  doc.setFont('helvetica', 'normal');
  doc.text('SHA-256 Cryptographic Hash', margin + 50, detailsY + 21);

  if (entry.statement_hash) {
    doc.setFont('helvetica', 'bold');
    doc.text('Hash:', margin + 5, detailsY + 28);
    doc.setFont('courier', 'normal');
    doc.setFontSize(7);
    const hash = entry.statement_hash;
    doc.text(hash.substring(0, 64), margin + 50, detailsY + 28);
  }

  y += 50;

  // Section 2: Incident Record
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(40);
  doc.text('INCIDENT RECORD', margin, y);
  y += 8;

  const addField = (label: string, value: string | null | undefined) => {
    if (!value) return;
    checkPage(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(80);
    doc.text(`${label}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(40);
    const lines = doc.splitTextToSize(value, contentWidth - 45);
    doc.text(lines, margin + 45, y);
    y += Math.max(6, lines.length * 4.5) + 2;
  };

  addField('Date', formatDate(entry.entry_date));
  addField('Time', entry.entry_time?.slice(0, 5));
  addField('Person Involved', entry.about_person || 'Not specified');

  // Description
  checkPage(20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text('Incident Description:', margin, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(40);
  doc.setFontSize(10);
  const descLines = doc.splitTextToSize(entry.incident_description, contentWidth);
  for (const line of descLines) {
    checkPage(6);
    doc.text(line, margin, y);
    y += 5;
  }
  y += 4;

  addField('Type of Abuse', entry.abuse_types?.join(' • ') || 'Not specified');
  addField('Weapon Involved', entry.weapon_involved ? `Yes — ${entry.weapon_description || 'Details not provided'}` : 'No');
  addField('Medical Attention', entry.medical_attention ? `Yes — ${entry.medical_details || 'Details not provided'}` : 'No medical attention sought');
  addField('Police Report', entry.police_reported ? `Yes — Case number: ${entry.police_case_number || 'Pending'}` : 'No police report made');
  addField('Children Present', entry.children_present ? 'Yes' : 'No');
  addField('Location', entry.location || 'Not specified');
  addField('Witnesses', entry.witnesses || 'None recorded');
  addField('Injuries/Damage', entry.injuries_damage || 'None recorded');
  addField('Emotional State', entry.emotional_state || 'Not recorded');

  // Evidence section
  if (evidence.length > 0) {
    checkPage(20);
    doc.setFillColor(245, 245, 245);
    doc.rect(margin, y, contentWidth, 8, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(60);
    doc.text(`Evidence Attached: ${evidence.length} file(s)`, margin + 3, y + 6);
    y += 12;

    for (const ev of evidence) {
      checkPage(20);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(60);
      doc.text(`File: ${ev.file_name}`, margin + 3, y);
      doc.text(`Type: ${ev.file_type} | Size: ${formatFileSize(ev.file_size)}`, margin + 3, y + 5);
      if (ev.file_hash) {
        doc.setFont('courier', 'normal');
        doc.setFontSize(7);
        doc.text(`Hash: ${ev.file_hash}`, margin + 3, y + 10);
        y += 14;
      } else {
        y += 9;
      }
      doc.setDrawColor(200);
      doc.line(margin, y, pageWidth - margin, y);
      y += 4;
    }
  }

  // Legal Notice
  checkPage(80);
  doc.setDrawColor(124, 58, 237);
  doc.setLineWidth(1.5);
  doc.line(margin, y, margin, y + 75);
  doc.setFillColor(237, 233, 254);
  doc.rect(margin + 2, y, contentWidth - 2, 75, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(124, 58, 237);
  doc.text('LEGAL NOTICE', margin + 5, y + 7);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(60);
  const legalText = [
    'This document is a RedFlaq Verified Safety Record generated from the RedFlaq My Safety Journal platform.',
    '',
    'CRYPTOGRAPHIC VERIFICATION: The incident description was cryptographically hashed at the time of saving using SHA-256 verification. Any alteration to the original statement after verification would produce a different hash value, making tampering immediately detectable.',
    '',
    'LEGAL STATUS IN SOUTH AFRICA: Under the Electronic Communications and Transactions Act 25 of 2002 (ECTA), Section 15, digital records may be admitted as evidence in South African legal proceedings when they can be shown to be complete, unaltered, and properly authenticated.',
    '',
    'IMPORTANT LIMITATIONS:',
    '- This document does NOT replace a commissioned affidavit sworn before a Commissioner of Oaths',
    '- This document does NOT constitute legal advice',
    '- This document does NOT guarantee court admissibility',
    '',
    'RECOMMENDED: Always consult with Legal Aid South Africa (0800 110 110) or a qualified attorney.',
    'To report GBV: Call 0800 428 428 (24/7) or SAPS 10111.',
  ];
  
  let ly = y + 13;
  for (const line of legalText) {
    const wrapped = doc.splitTextToSize(line, contentWidth - 12);
    for (const w of wrapped) {
      doc.text(w, margin + 5, ly);
      ly += 3.5;
    }
  }

  addFooter();
  doc.save(`RedFlaq_Certificate_${entry.entry_date}_${entry.id.slice(0, 8)}.pdf`);
}
